### ISSUE TITLE
gin pretrained files cannot be loaded

### ISSUE THREAD

**Issue by MarieOestreich** [yuyangw/MolCLR#1]
Hi,
when trying to load the pre-trained GIN model with torch, load, we were facing an error. According to our google search it it due to a corrupted file. 
In Google Colab we get this error: '
RuntimeError: PytorchStreamReader failed reading zip archive: failed finding central directory'

It would be great if you could re-upload the file.
Thanks!

**Comment by yuyangw** [comment]
Hi, 
I checked the file and it can be correctly loaded on my side. 
Did you load the pre-trained model via `model.load_state_dict(torch.load(PATH))`?

**Comment by MarieOestreich** [comment]
Hi, thanks for your fast reply.
We only tried to load the entire model with `torch.load(PATH)`, which caused the error.
Now I tried your proposed `model.load_state_dict(torch.load(PATH))` and it works just fine.

Cheers!
