### ISSUE TITLE
Some issues about code in finetune.py?

### ISSUE THREAD

**Issue by githubXin123** [yuyangw/MolCLR#11]
Hi, thanks for your nice work!

https://github.com/yuyangw/MolCLR/blob/fe603e04807eab7a6c1e02e28881f72e2c67bcde/finetune.py#L124
The name of the prediction section is ‘’pred_head“ in [ginet_finetune.py].If I use GIN to finetune, should 'pred_lin' be changed to 'pred_head' on line 124?

**Comment by yuyangw** [comment]
Hi, thanks for pointing this out! I didn't notice this when doing code clean-ups. 
I have pushed a commit and fixed the issue. 

Best, 
Yuyang
