### ISSUE TITLE
Scaffold Split MUV ROC-AUC of MUC Dataset

### ISSUE THREAD

**Issue by JongKook-Heo** [yuyangw/MolCLR#13]
Hi, @yuyangw ,  I have a question about Scaffold Split and ROC-AUC in MUV Dataset!!

About three weeks ago, I received the answer, "For MUV, in rare cases where only one class is included in y_true, we calculate the accuracy instead of ROC-AUC."

Is that mean the ROC-AUC Score of the table 1 in your paper shows the mixed value of mostly ROC-AUC and few accruacy for above rare case??

If Not, How can I reproduce the adequate scaffold split sets of MUV by your code implementation?

**Comment by yuyangw** [comment]
Hi @JongKook-Heo, thanks for your interest in our work!
Yes, as I mentioned, in few cases of MUV where ROC-AUC is not available, we calculated accuracy instead. 
Hope this helps!

Best, 
Yuyang
