### ISSUE TITLE
Random split for QM9

### ISSUE THREAD

**Issue by yeondukim** [yuyangw/MolCLR#14]
Hi @yuyangw :)

I've found the valid and test indexes are shared in the case of the random split (especially for QM9). 
https://github.com/yuyangw/MolCLR/blob/dd87b5f4ab8719616ba3a3d2e64759299ae46e18/dataset/dataset_test.py#L201

I guess it should be this manner.
```valid_idx, test_idx, train_idx = indices[:split], indices[split:split+split2], indices[split+split2:]```

**Comment by yuyangw** [comment]
Hi @yeondukim,

Thanks for pointing this out. I've fixed this in the latest update. 

Best, 
Yuyang
