### ISSUE TITLE
Calculating the mean value for multi-target dataset in Table1 and Table2

### ISSUE THREAD

**Issue by JongKook-Heo** [yuyangw/MolCLR#17]
Hi, Yuyang Wu!

I'm wondering if, for multi-target tasks, each mean value per data in the table1 and table2 in your paper consists of different hyperparameter settings. (i.e, picking heterogeneous(best performed for each target) hyper-parameter combinations in ClinTox and take the average for individual run). 

Best regards,
JongKook, Heo

**Comment by yuyangw** [comment]
Hi JongKook, that is correct.
