### ISSUE TITLE
How to Get Chirality tag and BondDir for canonical smiles

### ISSUE THREAD

**Issue by shrimonmuke0202** [yuyangw/MolCLR#22]
Hi Team,

I have a canonical smile "CCC[NH2+]C(CCc1ccccn1)c1ccc(Cl)s1" and obtain rdkit.Chem.rdchem.ChiralType.CHI_UNSPECIFIED as chiral tag and rdkit.Chem.rdchem.BondDir.NONE for all atoms and bonds. Why does this happen? is there any alternative way to include those two properties in the molecular graph?

Again for all smiles strings that are used for pertaining of the iMolCLR produces rdkit.Chem.rdchem.ChiralType.CHI_UNSPECIFIED for chiraltag and rdkit.Chem.rdchem.BondDir.NONE for BondDIR.

**Comment by yuyangw** [comment]
See [https://github.com/yuyangw/iMolCLR/issues/6](https://github.com/yuyangw/iMolCLR/issues/6).
