### ISSUE TITLE
Code for iMolCLR

### ISSUE THREAD

**Issue by colormeblue1013** [yuyangw/MolCLR#5]
Dear author, 

Recently I've read your iMolCLR paper. And I'd like to know if you have the plans to publish the code for it. 

Many thanks,
Lixin

**Comment by yuyangw** [comment]
Hi Lixin, 

Thanks for your interest in our work. The iMolCLR paper is now under review. We'll release the code as soon as the paper gets published. 

Best

**Comment by colormeblue1013** [comment]
Thanks. Looking forward to it!

Just one more question about the experiments. I saw you mentioned "The model is trained with batch size 512 for the total 50 epochs" in the MolCLR paper. But I'm curious about how much time it cost you to pretrain the MolCLR/iMolCLR model and how many GPUs you used.   

Many thanks.

**Comment by yuyangw** [comment]
It takes 3-4 days to pre-train MolCLR on a single RTX 6000 and iMolCLR takes a bit longer. Hope this helps!
