### ISSUE TITLE
Apex support

### ISSUE THREAD

**Issue by peizhenbai** [yuyangw/MolCLR#6]
Hi @yuyangw 

Awesome work about molecule pre-training! I see you provided the apex support for mixed-precision training. Since I have not tried the package before, may I ask whether it is obvious to accelerate model training, and how is the performance gap compared to non-apex support?

Many thanks.
Peizhen

**Comment by yuyangw** [comment]
Hi Peizhen, 

Thanks for your kind words. The apex package can train and store the NN model in mixed-precision of float16 and float32. This saves the GPU memory and optimizes the matrix operations during training. Thus, apex accelerates the training and enables larger batch size with limited GPU memory. More details can be found in apex official GitHub repo: [https://github.com/NVIDIA/apex](https://github.com/NVIDIA/apex). 

Hope this helps!

Best, 
Yuyang

**Comment by peizhenbai** [comment]
Thanks for your quick reply, Yuyang! It's very helpful :-)
