### ISSUE TITLE
Questions about Calculating ROC-AUC of MUV Dataset

### ISSUE THREAD

**Issue by JongKook-Heo** [yuyangw/MolCLR#8]
Hi, @yuyangw , thanks for sharing your nice works!

I have some questions about calculating ROC-AUC in MUV Dataset.

As you know, there are very few positive(label=1) data in MUV.

So when I'm trying to get ROC-AUC following your scaffold split and metric evaluation(), I encounter with the problem that ONLY ONE CLASS present in y_true.

Can I ask you how did you cope with that problem?

###Further Question!(Simple)##
For multiple label task, Is it right that Each individual run result in Table 1 and Table2 is the average for whole tasks?
And then stdev must be considered by '# of runs' not by '# of runs * # of tasks'. Is that correct?

Thanks!!!

**Comment by yuyangw** [comment]
Hi @JongKook-Heo,

Thanks for your interest in our work. For MUV, in rare cases where only one class is included in y_true, we calculate the accuracy instead of ROC-AUC. 
And yes, the std is considered by the number of runs and averaged over all tasks. 

Hope this helps.

Best,
Yuyang

**Comment by JongKook-Heo** [comment]
Thanks for your kind reply!! And I feel sorry for late response, but I have one more question.

In that case, Yot mean that the MUV result table in your paper shows the mixed value of ROC-AUC(Mostly) and Accuracy(Only for one class in y_true case)?? 

Best regards,
Jong Kook, Heo
