### ISSUE TITLE
Questions about experimental results of Strategies for pre-training graph neural networks

### ISSUE THREAD

**Issue by zhenyuhe00** [yuyangw/MolCLR#9]
Hi, thanks for your nice work!

I find that the performance of Strategies for pre-training graph neural networks in your paper is different from the original paper. I wonder why is that, did you use different experimental settings?

Thanks!

**Comment by yuyangw** [comment]
Hi, 

Thanks for your interest in our work.

We re-run the model and did further fine-tuning following the same experimental setting in MolCLR. The paper reported the results we obtained on our end.

Hope this helps.

Best, 
Yuyang
